### ISSUE TITLE
Incongruenze fra traduzione e originale.

### ISSUE THREAD

**Issue by RaydenMK** [ScrappyCocco/PlanetCoasterItalian#35]
Vista la peculiare traduzione di "Manager stagionali" sono andato a vedere le corrispondenti righe nel file 1.3.1 originale.. a parte la numerazione differente, le righe fanno riferimento ad elementi completamente diversi. Come mai?
Versione ITA

entry key="FrontEndMenu_DifficultyHard_Description" translation="Budget Iniziale: $2000 (no loans available)&#10;Tasso di Restituzione: 25%&#10;&#10;Ricerca lenta e costosa&#10;I visitatori diventano tristi in fretta &#10;Le attrazioni si rovinano in fretta"
<entry key="FrontEndMenu_DifficultyHarder" translation="Harder"
<entry key="FrontEndMenu_DifficultyHarder_Description" translation="Per i Manager stagionali&#10;I visitatori sono difficili da attirare e le attrazioni perdono attirazione con il tempo"
<entry key="FrontEndMenu_DifficultyHarder_DescriptionALT" translation="Per i Manager stagionali"
<entry key="FrontEndMenu_DifficultyMedium" translation="Media"
<entry key="FrontEndMenu_DifficultyMedium_Description" translation="Budget Iniziale: $4000&#10;Tasso di Restituzione: 50%&#10;&#10;Ricerca con costo e velocità normali&#10;La felicità dei visitatori è normale&#10;Le attrazioni si rovinano in tempi standard"/> 

Versione EN
FrontEndMenu_DifficultyHard_Description" translation="Starting cash: $2000

- Few items researched
- Guest Happines drops quickly
- Breakdown rate is fast
- Ride Reputation declines quickly"/><entry key="FrontEndMenu_DifficultyHarder" translation="Harder"/><entry key="FrontEndMenu_DifficultyHarder_Description" translation="Starting cash: $2000

- Few items researched
- Guest Happiness drops very quickly
- Breakdown rate is fast
- Ride Reputation declines very quickly
- Guests are harder to attract"/><entry key="FrontEndMenu_DifficultyHarder_DescriptionALT" translation="Starting cash: $2000

- Few items researched
- Guest Happiness drops very quickly
- Breakdown rate is fast
- Ride Reputation declines very quickly
- Guests are harder to attract"/><entry key="FrontEndMenu_DifficultyMedium" translation="Medium"/><entry key="FrontEndMenu_DifficultyMedium_Description" translation="Starting cash: $4000

- Some items researched
- Guest Happiness drops steadily
- Breakdown rate is average
- Ride Reputation declines steadily"/>

**Comment by RaydenMK** [comment]
Hanno appena postato la stringa 1.3.9 (YEAHHHH!) e ad esempio questa parte evidenziata è ancora simile alla precedente in inglese, quindi molto diversa da quanto tradotto in italiano.. 
Probabilmente era così in qualche versione precedente, ma ora è diversa.
Dovremo dare un'occhiata generale a tutta la traduzione (giunta a 20242 stringhe! XD)!

**Comment by ScrappyCocco** [comment]
Come detto nella pull intanto penso ad unire la tua pull e fare il merge, poi controlliamo 😄

**Comment by ScrappyCocco** [comment]
A parte il fatto che non si capisce molto da come hai pubblicato la cosa ahah quindi la prossima volta cerca di usare la sezione codice apposita, non saprei dirti, potrebbe essere che sia una traduzione errata com'è successo con altre. 
Ho aggiornato il mio file alle 1.3.9, ti consiglio di farti la pull per aggiornarti il tuo (e ricrearti il branch beta), una volta aggiornato il file affidati al file 1.3.9 originale per ogni dubbio, è l'unico modo...

**Comment by RaydenMK** [comment]
Ahahahahah  :grin: Mi sono capito solo io... Intendevo dire che questa parte di traduzione non corrisponde all'originale inglese. E non è neanche una libera interpretazione, credo. Quindi o si tratta della traduzione di una vecchia versione o il traduttore ha molta fantasia  :grin:
Faccio il merge  :thumbsup:

**Comment by ScrappyCocco** [comment]
Esatto quindi forse è solo sbagliata, se in inglese dice una certa cosa correggi pure
